app/socialmedia/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),

    path('account/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from user import views

app_name = 'user'

handler404 = 'user.views.redirectPNF' # Added this line in URLconf instead of settings.py


urlpatterns = [
    path('signup', SignUpView, name='signup'),
    path('login', LoginView, name='login'),
    path('logout', LogoutView, name='logout'),

]

app/pages/templates/pages/about.html
{% extends "base_pages.html" %}

app/pages/templates/pages/index.html
{% extends "base_pages.html" %}
{% block title %} YOUniverse {% endblock %}

{% block content %}

        <section>
            <div class="index-info">
                <div class="logo">
                    <span class="title">YOUniverse</span><br/><br/>
                    <span>Don't let the<strong> curiosity </strong>kill you!<br/></span> 
                </div>
                <div class="buttons-index">
                    <a class="btn btn-auth inverse" href="{% url 'user:login' %}">Login</a>
                    <a class="btn btn-auth" href="{% url 'user:signup' %}">Sign Up</a>
                </div> 
            </div>
        </section>
{% endblock %}