app/pages/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from pages import views, htmx_views

app_name = 'pages'

handler404 = 'pages.views.redirectPNF' # Added this line in URLconf instead of settings.py

urlpatterns = [
    path('', IndexView, name='index'),
    path('about', AboutView.as_view(), name='about'),
    path('home/', views.homeView, name='home'),
    path('inbox/', views.inboxView, name='profile-inbox'),
    path('notifications/', views.notificationsView, name='notifications'),
    path('save_question',htmx_views.save_question, name = "save-question"),
    path('get_questions_by_user',htmx_views.get_questions_by_user, name = "get-questions-by-user"),
    path('<str:user>/', views.profileDetailView, name='profile-detail'),
    path('<str:user>/edit/', views.editProfileView, name='profile-edit'),
    path('block_user_inbox/<str:user>',htmx_views.block_user_inbox, name = "block-user-inbox"),
    path('block_user_post/<str:user>',htmx_views.block_user_post, name = "block-user-post"),
    path('delete_question/<int:id>',htmx_views.delete_question, name = "delete-question"),
    path('get_question_by_id/<int:id>',htmx_views.get_question_by_id, name = "get-question-by-id"),
    path('save_answer/<int:id>',htmx_views.save_answer, name = "save-answer"),
    path('get_posts/<str:user>',htmx_views.get_posts, name = "get-posts"),

    path('<str:user>/post/<int:id>',views.postDetailView, name = "post-detail"),
    path('<str:user>/post/<int:id>/edit',htmx_views.edit_post, name = "edit-post"),

    path('get_post/<int:id>',htmx_views.get_post, name = "get-post"),
    path('like_post/<int:id>',htmx_views.like_post, name = "like-post"),
    path('share_post/<int:id>',htmx_views.share_post, name = "share-post"),
    path('delete_post/<int:id>',htmx_views.delete_post, name = "delete-post"),

    path('follow_unfollow_user/<str:user>',htmx_views.follow_unfollow_user, name = "follow-unfollow-user"),
    path('mute_unmute_user/<str:user>',htmx_views.mute_unmute_user, name = "mute-unmute-user"),
    path('block_unblock_profile/<str:user>',htmx_views.block_unblock_profile, name = "block-unblock-profile"),
    
]

app/socialmedia/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),

    path('account/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from user import views

app_name = 'user'

handler404 = 'user.views.redirectPNF' # Added this line in URLconf instead of settings.py


urlpatterns = [
    path('signup', SignUpView, name='signup'),
    path('login', LoginView, name='login'),
    path('logout', LogoutView, name='logout'),

]

app/user/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.urls import reverse 
from itertools import chain
from .managers import ProfileManager
from pages.notifications import notifications_count

class Profile(models.Model):
    """Model representing an user."""
    user = models.OneToOneField(User, on_delete=models.CASCADE, default = "")
    icon = models.ImageField(default='defaults/user.png')
    following = models.ManyToManyField(User, related_name='following', blank = True)
    blocked = models.ManyToManyField(User, related_name='blocked_users', blank = True)
    silenced = models.ManyToManyField(User, related_name='silenced_users', blank = True)
    question_helper = models.TextField(max_length=200, default = "Ask me anything !", null=True, blank=True)
    allow_anonymous_questions = models.BooleanField(default = True)

    objects = models.Manager()
    profiles = ProfileManager()

    def get_absolute_url(self):
        """Returns the url to access a particular profile."""
        return reverse('profile-detail', args=[self.user.username])

    def __str__(self):
        """String for representing the Model object."""
        return str(self.user)

    def get_user(self):
        """String for representing the Model object."""
        return str(self.user.username)

    @property
    def notif_count(self):
        return notifications_count(self.user)

    """FOLLOWING METHODS"""
    def get_following(self):
        """Returns the users the account is following."""
        return self.following.all()

    def get_following_users(self):
        """Returns a list of users the account is following."""
        following_list = [user for user in self.get_following()]
        return following_list

    @property
    def following_count(self):
        """Returns the number of users the account is following."""
        return self.get_following().count()


    """FOLLOWERS METHODS"""    
    def get_followers(self):
        query_set = Profile.objects.all()
        followers_list = []
        for profile in query_set:
            if self.user in profile.get_following():
                followers_list.append(profile.user)

        return followers_list

    @property
    def followers_count(self):
        """Returns the number of users the account is following."""
        return len(self.get_followers())


    """SILENCED METHODS"""
    def get_silenced(self):
        """Returns the users the account blocked."""
        return self.silenced.all()

    def get_silenced_users(self):
        """Returns a list of users the account blocked."""
        silenced_list = [user for user in self.get_silenced()]
        return silenced_list

    @property
    def silenced_count(self):
        """Returns the number of users the account blocked."""
        return self.get_silenced().count()

    
    """SILENCED BY METHODS"""
    def get_silenced_by_users(self):
        """Returns a list of users that blocked the account."""
        query_set = Profile.objects.all()
        silenced_by_list = []
        for profile in query_set:
            if self.user in profile.get_silenced_users():
                silenced_by_list.append(profile.user)

        return silenced_by_list

    @property
    def silenced_by_count(self):
        """Returns the number of users the account blocked."""
        return len(self.get_silenced_by_users())


    """BLOCKED METHODS"""
    def get_blocked(self):
        """Returns the users the account blocked."""
        return self.blocked.all()

    def get_blocked_users(self):
        """Returns a list of users the account blocked."""
        blocked_list = [user for user in self.get_blocked()]
        return blocked_list

    @property
    def block_count(self):
        """Returns the number of users the account blocked."""
        return self.get_blocked().count()

    
    """BLOCKED BY METHODS"""
    def get_blocked_by_users(self):
        """Returns a list of users that blocked the account."""
        query_set = Profile.objects.all()
        blocked_by_list = []
        for profile in query_set:
            if self.user in profile.get_blocked_users():
                blocked_by_list.append(profile.user)

        return blocked_by_list

    @property
    def block_by_count(self):
        """Returns the number of users the account blocked."""
        return len(self.get_blocked_by_users())

    
    """POSTS METHODS"""  
    def get_my_posts(self):
        posts = [self.post_set.all()]
        query_set = None

        if len(posts) > 0:
            query_set = sorted(chain(*posts), reverse = True, key=lambda obj: obj.created_at)
        return query_set

    @property
    def posts_count(self):
        return self.post_set.all().count()

    def get_my_and_following_posts(self):
        users = [user for user in self.get_following()]
        posts = []
        query_set = None
        for u in users:
            profile = Profile.objects.get(user = u)
            profile_posts = profile.post_set.all()
            posts.append(profile_posts)

        my_posts = self.post_set.all()
        posts.append(my_posts)

        if len(posts) > 0:
            query_set = sorted(chain(*posts), reverse = True, key=lambda obj: obj.created_at)
        
        return query_set
    

    

app/user/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .validators import validate_email
from .models import Profile

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(validators = [validate_email])

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
        ]

class ProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = [
            'icon',
            'question_helper',
            'allow_anonymous_questions',
        ]

app/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .forms import UserRegistrationForm
from .models import Profile, User

# Create your views here.

def redirectPNF(request, exception): return redirect('home')

@user_passes_test(lambda user: not user.username, login_url='/home', redirect_field_name=None)
def SignUpView(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)

            return redirect('/home')
    else:
        user_form = UserRegistrationForm()
        
    
    return render(request, 'user/signup.html', {'user_form': user_form})

#if user is already logged in, redirect to 'home' page.
@user_passes_test(lambda user: not user.username, login_url='/home', redirect_field_name=None)
def LoginView(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/home')
        else:
            form_login = AuthenticationForm()
    else:
        form_login = AuthenticationForm()
    return render(request, 'user/login.html', {'form_login': form_login})

def LogoutView(request):
    logout(request)
    return redirect('/')

app/user/templates/profiles/partials/list_all_questions.html
{% if questions %}
   {% for question in questions %}
   <div class="question-container">
    <div class="question-sender">
        <div class="icon">

        </div>
        <span class="username"> 
            <b>
            {% if question.is_anon == False %}
            <a href="{% url 'user:profile-detail' question.sent_by %}"> 
                {{ question.sent_by}}    </a>
                     
            {% else %}
                anonymous
            {% endif %} 
            </b>
            asked you
        </span>
    </div>
    <div class="question-body">
        {{question.body|truncatechars:285}}
        {% if question.body|length > 285%}
        <a   href=""
                type="button"
                hx-get="{%url 'user:get-question-by-id' question.id %}"
                hx-trigger="click"
                hx-target=".inbox-main">...Read more</a>
        {% endif %}
    </div>
    <div class="question-action">
       <div class="action-container">
        <button class="btn inverse" 
                hx-get="{%url 'user:get-question-by-id' question.id %}"
                hx-trigger="click"
                hx-target=".inbox-main">
                Reply
        </button>
       </div>
       <div class="action-container" hx-confirm="Are you sure?">
        <button class="btn-htmx"
                type="button"
                hx-delete="{%url 'user:block-user' question.sent_by %}"
                hx-trigger="click"
                hx-target=".inbox-main"
                name="Block user"
                >
            <li class="action" id="action-block"><i class="fi fi-rr-cross-circle"></i></i></li>
        </button>
        
        <button class="btn-htmx"
                type="button"
                hx-delete="{%url 'user:delete-question' question.id %}"
                hx-trigger="click"
                hx-target=".inbox-main"
                name="Delete question"
                >

        <li class="action" id="action-delete"><i class="fi fi-rr-trash"></i></i></li>
        </button>
       </div>
    </div>
    
   </div>
   {% endfor %}
{% else %}
   <div class="object-not-found">
    <b>Your inbox is empty.</b> 

  </div>

{% endif %}

app/user/templates/profiles/partials/show_question.html
<div class="question-reply-container">
    <div style="display: flex;">
        <div class="question-sender">
            <div class="icon">

            </div>
            <span class="username"> 
                <b>
                {% if question.is_anon == False %}
                <a href="{% url 'user:profile-detail' question.sent_by %}"> 
                    {{ question.sent_by}}    </a>
                        
                {% else %}
                    anonymous
                {% endif %} 
                </b>
                asked you
            </span>
            
        </div>
        <div class="back-questions">
            <button class="btn-htmx"
                    hx-get="{% url 'user:get-questions-by-user' %}"
                    hx-trigger="click"
                    hx-target=".inbox-main">
                    <i class="fi fi-br-cross"></i>
            </button>
        </div>
    </div>
    
    <div class="question-body">
        {{question.body}}
    </div>
    <div class="question-reply">
        <form method="post">
        {% csrf_token %}
            <textarea id="message-reply" name="body" required></textarea><br>
            <div class="action-container">
                <button class="btn btn-reply " 
                        hx-post="{%url 'user:save-answer' question.id %}"
                        hx-trigger="click"
                        hx-target=".inbox-main">
                        Post
                </button>
            </div>
        </form>
    </div>
    
   </div>