app/pages/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from pages import views, htmx_views

app_name = 'pages'

handler404 = 'pages.views.redirectPNF' # Added this line in URLconf instead of settings.py

urlpatterns = [
    path('', IndexView, name='index'),
    path('about', AboutView.as_view(), name='about'),
    path('home/', views.homeView, name='home'),
    path('inbox/', views.inboxView, name='profile-inbox'),
    path('notifications/', views.notificationsView, name='notifications'),
    path('save_question',htmx_views.save_question, name = "save-question"),
    path('get_questions_by_user',htmx_views.get_questions_by_user, name = "get-questions-by-user"),
    path('<str:user>/', views.profileDetailView, name='profile-detail'),
    path('<str:user>/edit/', views.editProfileView, name='profile-edit'),
    path('block_user_inbox/<str:user>',htmx_views.block_user_inbox, name = "block-user-inbox"),
    path('block_user_post/<str:user>',htmx_views.block_user_post, name = "block-user-post"),
    path('delete_question/<int:id>',htmx_views.delete_question, name = "delete-question"),
    path('get_question_by_id/<int:id>',htmx_views.get_question_by_id, name = "get-question-by-id"),
    path('save_answer/<int:id>',htmx_views.save_answer, name = "save-answer"),
    path('get_posts/<str:user>',htmx_views.get_posts, name = "get-posts"),

    path('<str:user>/post/<int:id>',views.postDetailView, name = "post-detail"),
    path('<str:user>/post/<int:id>/edit',htmx_views.edit_post, name = "edit-post"),

    path('get_post/<int:id>',htmx_views.get_post, name = "get-post"),
    path('like_post/<int:id>',htmx_views.like_post, name = "like-post"),
    path('share_post/<int:id>',htmx_views.share_post, name = "share-post"),
    path('delete_post/<int:id>',htmx_views.delete_post, name = "delete-post"),

    path('follow_unfollow_user/<str:user>',htmx_views.follow_unfollow_user, name = "follow-unfollow-user"),
    path('mute_unmute_user/<str:user>',htmx_views.mute_unmute_user, name = "mute-unmute-user"),
    path('block_unblock_profile/<str:user>',htmx_views.block_unblock_profile, name = "block-unblock-profile"),
    
]

app/socialmedia/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),

    path('account/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from user import views

app_name = 'user'

handler404 = 'user.views.redirectPNF' # Added this line in URLconf instead of settings.py


urlpatterns = [
    path('signup', SignUpView, name='signup'),
    path('login', LoginView, name='login'),
    path('logout', LogoutView, name='logout'),

]

app/pages/templates/profiles/partials/edit_post.html
<div class="post">
  <div style="display: flex;">
      <div class="post-question">
          {{post.answer.question}}</br>
          <span class="question-author">
          <i class="fi fi-sr-user"></i>
          {%if post.answer.question.is_anon == False%}
              <a href="{% url 'pages:profile-detail' post.answer.question_author %}">{{post.answer.question_author}} </a>
          {%else%}
              Anon
          {%endif%}
          </span>

      </div>
      <div class="back-posts">
          <i  class="fi fi-br-cross"
              type="button"
              hx-get="{% url 'pages:get-posts' request.user.username %}"
              hx-trigger="click"
              hx-target=".posts-container"    
          ></i>
      </div>
  </div>

      <div class="answer-content">
          <form method="post">
              {% csrf_token %}
              <div class="post-edit">
                  <textarea id="message-reply" name="body" required> {{ post.answer }} </textarea><br>

              </div>
              <div class="send-area">
                  <span></span>
                  <div class="message-button">
                      <button type="button" class="btn btn-msg"
                              hx-post="{%url 'pages:edit-post' request.user post.id %}"
                              hx-trigger="click" 
                              hx-target=".posts-container"
                      > Save </button>
                  </div>
             </div>
          </form>
      </div>
</div>

app/pages/templates/profiles/partials/like_button.html
<li
  class="action"
  id="action-like"
  type="button"
  hx-post="{%url 'pages:like-post' post.id %}"
  hx-trigger="click"
  hx-swap="outerHTML">
  {% if request.user in post.get_likes %}
    <i class="fi fi-sr-heart full"> {{post.like_count}} </i>
  {% else %}
    <i class="fi fi-sr-heart"> {{post.like_count}} </i>
  {% endif %}
</li>

app/pages/templates/profiles/partials/list_all_questions.html
{% if questions %}
   {% for question in questions %}
   <div class="question-container">
        <div class="question-sender">
            <div class="author-icon">
                {% if question.is_anon == False %}
                <img src={{question.sent_by.icon.url}} alt="">
                {% else %}
                <img src="../media/defaults/user.png" alt="">
                {% endif %} 
                
            </div>
            <span class="username"> 
                <b style="max-width: 100%;">
                {% if question.is_anon == False %}
                <a href="{% url 'pages:profile-detail' question.sent_by %}"> 
                    {{ question.sent_by}}    </a>
                {% else %}
                    anonymous
                {% endif %} 
                </b>
                asked you
            </span>
        </div>
        <div class="question-body-container">
            <div class="question-blank"> </div>
            <div class="question-body">
            {{question.body|slice:"0:264"}}
            {% if question.body|length > 264%}
            <a   href=""
                    type="button"
                    hx-get="{%url 'pages:get-question-by-id' question.id %}"
                    hx-trigger="click"
                    hx-target=".inbox-main">Read more</a>
            {% endif %}
            </div>
        </div>
        <div class="question-action">
            <div class="action-container">
                <button class="btn inverse" 
                        hx-get="{%url 'pages:get-question-by-id' question.id %}"
                        hx-trigger="click"
                        hx-target=".inbox-main">
                        Reply
                </button>
            </div>
            <div class="action-container" hx-confirm="Are you sure?">
                    <li class="action" id="action-block"
                        type="button"
                        hx-delete="{%url 'pages:block-user-inbox' question.sent_by %}"
                        hx-trigger="click"
                        hx-target=".inbox-main"
                        name="Block user">
                        <i class="fi fi-rr-cross-circle"></i></i>
                    </li>
                    <li class="action" id="action-delete"
                        type="button"
                        hx-delete="{%url 'pages:delete-question' question.id %}"
                        hx-trigger="click"
                        hx-target=".inbox-main"
                        name="Delete question">
                        <i class="fi fi-rr-trash"></i>
                    </li>
            </div>
        </div>
   </div>
   {% endfor %}
{% else %}
   <div class="object-not-found">
        <b>Your inbox is empty.</b> 

    </div>

{% endif %}

app/pages/templates/profiles/partials/list_posts.html
{% if request.user in profile.get_blocked_users %}
    <div class="object-not-found">
        <b> You are blocked! </b> 
        <b style="font-size: 1.2rem;"> You cannot follow or see <u>{{ username }}</u> posts.</b>
    </div>
{% else %}  
    {%if posts %}
        {% for post in posts%}
        <div class="post">
            <div class="post-question">
                {{post.answer.question}}</br>
                <span class="question-author">
                <i class="fi fi-sr-user"></i>
                {%if post.answer.question.is_anon == False%}
                    <a href="{% url 'pages:profile-detail' post.answer.question_author %}">{{post.answer.question_author}} </a>
                {%else%}
                    Anon
                {%endif%}
                </span>
            </div>

            <div class="post-answer">
                <div class="answer-content">
                    {{post.answer}} </br>
                </div>
                <div class="answer-author">
                    <div class="author-icon">
                        <div class="author-icon">
                            <img src={{post.author.icon.url}} alt="">
                        </div>
                    </div>
                    <span class="author-user">
                    <a href="{% url 'pages:profile-detail' post.author %}"> <b>{{post.author}} </b></a> 
                    </span> 
                    • 
                    <span class="post-creation">  
                    <a href="{% url 'pages:post-detail' post.author post.id %}"> {{post.get_whenpublished}}</a> 
                    </span>

                </div>
            </div>

            <div class="post-action-container">
                <div class="post-action">
                    {% include "profiles/partials/like_button.html"%}
                    {% include "profiles/partials/share_button.html"%}
                </div>
                <div class="post-action">
                {%if request.user != post.get_question_author and post.get_question_author != profile.user%}
                    <li class="action" id="action-block"
                        type="button"
                        hx-delete="{%url 'pages:block-user-post' post.answer.question_author %}"
                        hx-trigger="click"
                        hx-target=".posts-container"
                        hx-confirm="Are you sure you want to block ?"
                        name="Block user">
                        <i class="fi fi-rr-cross-circle"></i>
                    </li>
                {% endif %}

                {%if request.user == post.author.user %}
                    <li class="action" id="action-edit"
                        type="button"
                        hx-get="{%url 'pages:edit-post' request.user post.id %}"
                        hx-trigger="click"
                        hx-target=".posts-container"
                        name="Edit post">
                        <i class="fi fi-rr-edit"></i>
                    </li>
                    <li class="action" id="action-delete"
                        type="button"
                        hx-delete="{%url 'pages:delete-post' post.id %}"
                        hx-trigger="click"
                        hx-target="section"
                        hx-confirm="Are you sure you want to delete?"
                        name="Delete post">
                        <i class="fi fi-rr-trash"></i>
                    </li> 
                {% endif %}
                </div>
            </div>   

        </div>
        {% endfor %}
    {% else %}
        <div class="object-not-found">
            <b >This user hasn't answered any questions yet.</b> 
            <b style="font-size: 1.2rem;">Be the first one to ask <u>{{ username }}</u> anything!</b>
        </div>
    {%endif%}
{% endif %}

app/pages/templates/profiles/partials/profile_info.html
<div class="profile-header">
  <div class="profile-icon-container">
    <img src={{profile.icon.url}} alt="">
  </div>
  <div class= "profile-user"> 
      <h4><b>{{username}}</b></h4>
      {% if profile %}        
      <div class="user-actions">
          {%if request.user.username == profile.get_user %}
          <div class="edit-container">
              <button type="button" class="btn btn-follow"
                      hx-get="{%url 'pages:profile-edit' username %}"
                      hx-trigger="click" 
                      hx-disabled-elt="this"
                      hx-target="section"
                      hx-replace-url="true"
                      > 
                  Edit profile 
              </button>
          </div>
          {% elif request.user not in  profile.get_blocked_by_users %}
              {% if request.user not in profile.get_blocked_users%}
                  <div class="follow-container"
                      hx-post="{%url 'pages:follow-unfollow-user' username %}"
                      hx-trigger="click" 
                      hx-target=".profile-info"
                      hx-disabled-elt="this">
                      {% if request.user in profile.get_followers %}
                          <button type="button" class="btn inverse btn-unfollow"> Unfollow </button>
                      {% else %}
                          <button type="button" class="btn btn-follow"> Follow </button>
                      {% endif %}
                  </div>
              {% endif %}
          {% else %}
              <div class="follow-container"
                  hx-post="{%url 'pages:block-unblock-profile' username %}"
                  hx-trigger="click" 
                  hx-target="section"
                  hx-disabled-elt="this">
                  <button type="button" class="btn btn-unblock"> Unblock </button>
              </div>
          {% endif %}

          {%if request.user.username != profile.get_user %}
          <div class="profile-actions">
              {% if request.user not in  profile.get_blocked_by_users %}
              <li class="action" id="action-block-profile"
                  type="button"
                  hx-post="{%url 'pages:block-unblock-profile' username %}"
                  hx-trigger="click"
                  hx-target="section"
                  hx-confirm="Are you sure you want to block {{ username }} ?"
                  name="Block profile">
                  <i class="fi fi-rr-smile"></i>
              </li>
              {% else %}
              <li class="action" id="action-block-profile" name="Unblock profile">
                  <i class="fi fi-sr-face-eyes-xmarks"></i>
              </li>
              {% endif %}

              <li class="action" id="action-mute"
                  type="button"
                  hx-post="{%url 'pages:mute-unmute-user' username %}"
                  hx-trigger="click"
                  hx-target=".profile-info"
                  name="Mute profile">
                  {% if request.user not in  profile.get_silenced_by_users %}
                      <i class="fi fi-sr-volume"></i>
                  {% else %}
                      <i class="fi fi-sr-volume-slash muted"></i>
                  {% endif %}
              </li> 
          </div>
          {% endif %}
      </div>
      {% endif %}
  </div>
</div>
{% if request.user not in profile.get_blocked_users %}
<div class="profile-stats">
  <div class="stats">
      <span id="followers_count">{{profile.followers_count}}</span>
      <span>Followers</span>
  </div>
  <div class="stats">
      <span id="following_count">{{profile.following_count}}</span>
      <span>Following</span>
  </div>
  <div class="stats">
      <span id="posts_count">{{profile.posts_count}}</span>
      <span>Answers</span>
  </div>
</div>
<div class="grid">
  <div class="message-form-container">
      <form method="post" id="question-form" action="">
      {% csrf_token %}
          <input type="hidden" id="username" name="username" value={{profile.get_user}}>
          <textarea id="message" name="body" required
                  placeholder="{{profile.question_helper}}"
          ></textarea>
          

          <div class="send-area">
              <div>
              {%if request.user.username == profile.get_user %}
                  <input type="checkbox" name="anon" id="hide-name" disabled/>
              {% else %}
                  <input type="checkbox" name="anon" id="hide-name" checked/>
              {% endif %}
                  <label for="hide-name" style=" color: var(--grey);">Hide your name</label>
              </div>
          <div class="message-button">
              {% if profile %}
                  <button type="submit" class="btn btn-msg" value="Send" > Send </button>
                      
              {%else%}
                  <button type="submit" class="btn btn-msg" value="Send" disabled> Send </button>
              {%endif%}
          </div>
      </div>
      </form>
  </div>
  <dialog id="response-container">
  </dialog>
</div>
{% endif %}


{% block js %}
<script type="text/javascript" >
  $(document).on("submit", "#question-form", function (e) {
    e.preventDefault();

    var formData = $('#question-form').serialize();

    const content = document.getElementById("message")
    const msg = content.value;
    var message = "";
    if (msg.length < 4)
        message = "Question must contain at least 4 characters !";
    else if (msg.length > 1500)
        message = "Question must contain up to 1500 characters !";
    if (msg.length >= 4 && msg.length <= 1500) {
        
        $.ajax({
            type: "POST",
            url: "{% url 'pages:save-question' %}",
            data: formData,
            success: function (data) {
                message = data;
                $("#response-container").empty();
                var resp = "<p>"+message+"</p>"
                $("#response-container").append(resp);
                $("#message").val('');
                document.getElementById("response-container").showModal();
                
            },
        });
    }
    else{
        $("#response-container").empty();
        var resp = "<p>"+message+"</p>"
        $("#response-container").append(resp);
        document.getElementById("response-container").showModal();


    }
});

$(document).on("click", "#response-container", function () {
    $("#response-container").empty();
    document.getElementById("response-container").close();
})
</script>
{% endblock %}

app/pages/templates/profiles/partials/question_response.html
<div
  class="response-container"
  hx-get="{}"
  hx-trigger="click"
  hx-target="#message-response"
  hx-swap="delete"
>
  <div id="message-response">
    <p>{{message}}</p>
  </div>
</div>

app/pages/templates/profiles/partials/share_button.html
<li class="action" id="action-share"
    type="button"
    hx-post="{%url 'pages:share-post' post.id %}"
    hx-trigger="click"
    hx-swap="outerHTML">
    {% if request.user in post.get_shares %}
      <i class="fi fi-rr-share-square full"> {{post.share_count}} </i>
    {% else %}
      <i class="fi fi-rr-share-square"> {{post.share_count}} </i>
    {% endif %}
</li>

app/pages/templates/profiles/partials/show_question.html
<div class="question-reply-container">
  <div style="display: flex; justify-content: space-between;">
      <div class="question-sender">
          <div class="author-icon">
            <div class="author-icon">
                <img src={{question.sent_by.icon.url}} alt="">
            </div>
          </div>
          <span class="username"> 
              <b>
              {% if question.is_anon == False %}
              <a href="{% url 'pages:profile-detail' question.sent_by %}"> 
                  {{ question.sent_by}}    </a>

              {% else %}
                  anonymous
              {% endif %} 
              </b>
              asked you
          </span>

      </div>
      <div class="back-questions">
          <i  class="fi fi-br-cross"
              type="button"
              hx-get="{% url 'pages:get-questions-by-user' %}"
              hx-trigger="click"
              hx-target=".inbox-main"   
          ></i>

      </div>
  </div>

  <div class="question-body-reply">
      {{question.body}}
  </div>

  <div class="question-reply">
      <form method="post">
      {% csrf_token %}
          <textarea id="message-reply" name="body" required></textarea><br>
          <div class="send-area">
              <span></span>
              <div class="action-container">
                  <button class="btn btn-reply " 
                          hx-post="{%url 'pages:save-answer' question.id %}"
                          hx-trigger="click"
                          hx-target=".inbox-main">
                          Post
                  </button>
              </div>
          </div>
      </form>
  </div>

</div>