app/pages/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from pages import views, htmx_views

app_name = 'pages'

handler404 = 'pages.views.redirectPNF' # Added this line in URLconf instead of settings.py

urlpatterns = [
    path('', IndexView, name='index'),
    path('about', AboutView.as_view(), name='about'),
    path('home/', views.homeView, name='home'),
    path('inbox/', views.inboxView, name='profile-inbox'),
    path('notifications/', views.notificationsView, name='notifications'),
    path('save_question',htmx_views.save_question, name = "save-question"),
    path('get_questions_by_user',htmx_views.get_questions_by_user, name = "get-questions-by-user"),
    path('<str:user>/', views.profileDetailView, name='profile-detail'),
    path('<str:user>/edit/', views.editProfileView, name='profile-edit'),
    path('block_user_inbox/<str:user>',htmx_views.block_user_inbox, name = "block-user-inbox"),
    path('block_user_post/<str:user>',htmx_views.block_user_post, name = "block-user-post"),
    path('delete_question/<int:id>',htmx_views.delete_question, name = "delete-question"),
    path('get_question_by_id/<int:id>',htmx_views.get_question_by_id, name = "get-question-by-id"),
    path('save_answer/<int:id>',htmx_views.save_answer, name = "save-answer"),
    path('get_posts/<str:user>',htmx_views.get_posts, name = "get-posts"),

    path('<str:user>/post/<int:id>',views.postDetailView, name = "post-detail"),
    path('<str:user>/post/<int:id>/edit',htmx_views.edit_post, name = "edit-post"),

    path('get_post/<int:id>',htmx_views.get_post, name = "get-post"),
    path('like_post/<int:id>',htmx_views.like_post, name = "like-post"),
    path('share_post/<int:id>',htmx_views.share_post, name = "share-post"),
    path('delete_post/<int:id>',htmx_views.delete_post, name = "delete-post"),

    path('follow_unfollow_user/<str:user>',htmx_views.follow_unfollow_user, name = "follow-unfollow-user"),
    path('mute_unmute_user/<str:user>',htmx_views.mute_unmute_user, name = "mute-unmute-user"),
    path('block_unblock_profile/<str:user>',htmx_views.block_unblock_profile, name = "block-unblock-profile"),
    
]

app/socialmedia/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),

    path('account/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from user import views

app_name = 'user'

handler404 = 'user.views.redirectPNF' # Added this line in URLconf instead of settings.py


urlpatterns = [
    path('signup', SignUpView, name='signup'),
    path('login', LoginView, name='login'),
    path('logout', LogoutView, name='logout'),

]

app/templates/base_generic.html
{% load static %}
{% load user_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <!-- cropper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.css">

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Orelega+One&display=swap" rel="stylesheet">
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-solid-rounded/css/uicons-solid-rounded.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-bold-rounded/css/uicons-bold-rounded.css'>

    <!-- custom css & js -->
    <link rel="stylesheet" href="{% static 'socialmedia/style.css' %}">
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>
    
    <title>{% block title %} {% endblock title %} | YOUniverse </title>
  </head>
  <body>
    
    <header class="menu-header">
      <div class = "top-menu">
        <div class="logo-menu">
          <a  href="/">YOUniverse</a>
        </div>
          <nav class="nav-menu" >
            <ul class="nav-list"> 
              <li class="nav-icon {%if request.resolver_match.url_name == 'home'%} active {%endif%}">
                <a href="{% url 'pages:home' %}"> 
                  {%if request.resolver_match.url_name == 'home'%}
                  <i class="fi fi-sr-home"></i> 
                  {%else%}
                  <i class="fi fi-rr-home"></i> 
                  {%endif%}
                </a>
              </li>
              <li class="nav-icon {%if request.resolver_match.url_name == 'profile-detail' or request.resolver_match.url_name == 'post-detail' or request.resolver_match.url_name == 'profile-edit'%} active {%endif%}">
                <a href="{% url 'pages:profile-detail'  request.user %}"> 
                  {%if request.resolver_match.url_name == 'profile-detail' or request.resolver_match.url_name == 'post-detail' or request.resolver_match.url_name == 'profile-edit'%}
                  <i class="fi fi-sr-user"></i> 
                  {%else%}
                  <i class="fi fi-rr-user"></i> 
                  {%endif%}
                </a>
              </li>
              <li class="nav-icon {%if request.resolver_match.url_name == 'notifications'%} active {%endif%}">
                <a href="{% url 'pages:notifications'  %}">
                  {%if request.resolver_match.url_name == 'notifications'%}
                  <i class="fi fi-sr-bell"></i> 
                  {%else%}
                  <i class="fi fi-rr-bell"></i> 
                  {%endif%}
                  {% get_notifications_count request.user as notifications_count %}
                  {%if notifications_count > 0%}
                    <span class="message-count">{{notifications_count}}</span>
                  {%endif%}
                </a>
                
                
              </li>
              <li class="nav-icon {%if request.resolver_match.url_name == 'profile-inbox'%} active {%endif%}">
                <a href="{% url 'pages:profile-inbox'%}"> 
                  {%if request.resolver_match.url_name == 'profile-inbox'%}
                  <i class="fi fi-sr-envelope"></i> 
                  {%else%}
                  <i class="fi fi-rr-envelope"></i> 
                  {%endif%}
                  {% get_questions_count request.user as questions_count %}
                  {%if questions_count > 0%}
                    <span class="message-count">{{questions_count}}</span>
                  {%endif%}
                </a>
               
              </li>
              <li class="nav-icon">
                <a href="{% url 'user:logout'%}"> 
                  <i class="fi fi-rr-sign-out-alt"></i> 
                </a>
              </li>
            </ul>
          </nav>        
      </div>
    </header>
    
    <section>
      <div class="main-content">
        {% block content %}
        {% endblock content %}
      </div>
    </section>
    {% block js %}    {% endblock js %}   
  </body>
</html>